/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.gmail.arthurstrokov.plugin

import com.gmail.arthurstrokov.plugin.tasks.CreateMajorRelease
import com.gmail.arthurstrokov.plugin.tasks.CreateMinorRelease
import com.gmail.arthurstrokov.plugin.tasks.GitStatus
import com.gmail.arthurstrokov.plugin.utils.GitUtil
import org.gradle.api.Plugin
import org.gradle.api.Project

/**
 * A simple 'hello world' plugin.
 */
class TestGradleGitReleasePluginPlugin implements Plugin<Project> {
    void apply(Project project) {
        // Register a task
        project.tasks.register("checkGitStatus", GitStatus) {
            setGroup("git test release tasks")
        }
        project.tasks.register("checkCurrentTagVersion") {
            setGroup("git test release tasks")
            dependsOn("checkGitStatus")
            GitUtil.currentTagVersion
        }
        project.tasks.register("updateMajorReleaseTag", CreateMajorRelease) {
            setGroup("git test release tasks")
            dependsOn("checkGitStatus")
        }
        project.tasks.register("updateMinorReleaseTag", CreateMinorRelease) {
            setGroup("git test release tasks")
            dependsOn("checkGitStatus")
        }
        project.tasks.register("updateReleaseTag") {
            setGroup("git release tasks")
            def currentBrunch = GitUtil.currentBranch
            if (currentBrunch.contains("master")) {
                dependsOn("updateMajorReleaseTag")
            } else {
                dependsOn("updateMinorReleaseTag")
            }
        }
    }
}
